import {defineCustomElement} from "../commons/defineCustomElement.ts";
import {Undo} from "../components/menus/Undo.ts";
import {Redo} from "../components/menus/Redo";
import {Heading} from "../components/menus/Heading.ts";
import {FontFamily} from "../components/menus/FontFamily";
import {FontSize} from "../components/menus/FontSize";
import {Bold} from "../components/menus/Bold";
import {Italic} from "../components/menus/Italic";
import {Underline} from "../components/menus/Underline";
import {Strike} from "../components/menus/Strike";
import {Subscript} from "../components/menus/Subscript";
import {Superscript} from "../components/menus/Superscript";
import {Highlight} from "../components/menus/Highlight";
import {FontColor} from "../components/menus/FontColor";
import {Divider} from "../components/menus/Divider";
import {BulletList} from "../components/menus/BulletList";
import {OrderedList} from "../components/menus/OrderedList";
import {IndentDecrease} from "../components/menus/IndentDecrease";
import {IndentIncrease} from "../components/menus/IndentIncrease";
import {Align} from "../components/menus/Align";
import {Link} from "../components/menus/Link";
import {Todo} from "../components/menus/Todo";
import {LineHeight} from "../components/menus/LineHeight";
import {Quote} from "../components/menus/Quote";
import {Image} from "../components/menus/Image";
import {Video} from "../components/menus/Video";
import {Code} from "../components/menus/Code";
import {CodeBlock} from "../components/menus/CodeBlock";
import {Eraser} from "../components/menus/Eraser";
import {Hr} from "../components/menus/Hr";
import {Table} from "../components/menus/Table";
import {Break} from "../components/menus/Break";
import {Attachment} from "../components/menus/Attachment";
import {Fullscreen} from "../components/menus/Fullscreen";
import {Printer} from "../components/menus/Printer";
import {Emoji} from "../components/menus/Emoji";
import {Painter} from "../components/menus/Painter";
import {Ai} from "../components/menus/Ai.ts";
import {Container} from "../components/menus/Container.ts";
import {Custom} from "../components/menus/Custom.ts";


defineCustomElement('aie-undo', Undo);
defineCustomElement('aie-redo', Redo);
defineCustomElement('aie-brush', Painter);
defineCustomElement('aie-eraser', Eraser);
defineCustomElement('aie-heading', Heading);
defineCustomElement('aie-font-family', FontFamily);
defineCustomElement('aie-font-size', FontSize);
defineCustomElement('aie-bold', Bold);
defineCustomElement('aie-italic', Italic);
defineCustomElement('aie-underline', Underline);
defineCustomElement('aie-strike', Strike);
defineCustomElement('aie-link', Link);
defineCustomElement('aie-code', Code);
defineCustomElement('aie-subscript', Subscript);
defineCustomElement('aie-superscript', Superscript);
defineCustomElement('aie-highlight', Highlight);
defineCustomElement('aie-font-color', FontColor);
defineCustomElement('aie-divider', Divider);
defineCustomElement('aie-bullet-list', BulletList);
defineCustomElement('aie-ordered-list', OrderedList);
defineCustomElement('aie-indent-decrease', IndentDecrease);
defineCustomElement('aie-indent-increase', IndentIncrease);
defineCustomElement('aie-align', Align);
defineCustomElement('aie-todo', Todo);
defineCustomElement('aie-line-height', LineHeight);
defineCustomElement('aie-break', Break);
defineCustomElement('aie-quote', Quote);
defineCustomElement('aie-image', Image);
defineCustomElement('aie-video', Video);
defineCustomElement('aie-code-block', CodeBlock);
defineCustomElement('aie-hr', Hr);
defineCustomElement('aie-table', Table);
defineCustomElement('aie-attachment', Attachment);
defineCustomElement('aie-fullscreen', Fullscreen);
defineCustomElement('aie-printer', Printer);
defineCustomElement('aie-emoji', Emoji);
defineCustomElement('aie-ai', Ai);
defineCustomElement('aie-container', Container);
defineCustomElement('aie-custom', Custom);